on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy app
        run: |
          cd /var/www/Simple_static_site || git clone https://github.com/rznwk/Simple_static_site.git /var/www/Simple_static_site
          cd /var/www/Simple_static_site
          git pull origin main
